FROM golang:alpine AS builder

WORKDIR /app

COPY . .

RUN go mod init myapp || true
RUN go mod tidy

RUN go build -o main code.go

FROM alpine

WORKDIR /app

COPY --from=builder /app/main .

CMD ["./main"]